services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lingonika
      POSTGRES_HOST: db
    command: >
      sh -c "npm run migrate && npm run start"
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: database
    ports:
      - "${DATABASE_PORT:-8100}:5432"
    env_file:
      - .env.docker
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lingonika
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
