services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    command:
      npm run start

  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
