// APP

// Header component
export const PROFILE_MENU_VISIBILITY_CHANGED = 'PROFILE_MENU_VISIBILITY_CHANGED';

// GROUPS

// Groups header component
export const FROM_LANGUAGE_MENU_VISIBILITY_CHANGED = 'FROM_LANGUAGE_MENU_VISIBILITY_CHANGED';
export const TO_LANGUAGE_MENU_VISIBILITY_CHANGED = 'TO_LANGUAGE_MENU_VISIBILITY_CHANGED';
export const SELECTED_FROM_LANGUAGE_CHANGED = 'SELECTED_FROM_LANGUAGE_CHANGED';
export const SELECTED_TO_LANGUAGE_CHANGED = 'SELECTED_TO_LANGUAGE_CHANGED';

// Create group box component
export const CREATE_GROUP_FORM_VISIBILITY_CHANGED = "CREATE_GROUP_FORM_VISIBILITY_CHANGED";
export const GROUP_NAME_CHANGED = "GROUP_NAME_CHANGED";
